ALTER TABLE files ADD COLUMN IF NOT EXISTS skeleton TEXT;
ALTER TABLE files ADD COLUMN IF NOT EXISTS line_count INT;
ALTER TABLE features ADD COLUMN IF NOT EXISTS embed_hash TEXT;
ALTER TABLE module_tree ADD COLUMN IF NOT EXISTS embed_hash TEXT;
ALTER TABLE symbols ADD COLUMN IF NOT EXISTS summary_long_hash TEXT;
